name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install CMake and Ninja
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

      - name: Configure CMake (generate compile_commands.json)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          ls -l build/compile_commands.json

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.3
        with:
          args: --image jetbrains/qodana-clang:2025.3-eap --compile-commands build/compile_commands.json --fail-threshold 9999
          upload-result: true
          use-annotations: true
          # Do not fail the CI if Qodana itself fails internally
          fail-on-error: false
