name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Generate compile_commands.json
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Qodana Scan
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_883679330 }}
        run: |
          mkdir -p qodana-results

          docker run --rm \
            -u $(id -u):$(id -g) \
            -v $(pwd):/data/project \
            -v $(pwd)/qodana-results:/data/results \
            -e QODANA_TOKEN="$QODANA_TOKEN" \
            jetbrains/qodana-clang:2025.3-eap \
            --save-report
